# Doctrine.Tests.ORM.Mapping.User.dcm.yml
# in progress
Fabgg\JukeboxBundle\Model\JKFile:
    type: mappedSuperclass
    repositoryClass: Fabgg\JukeboxBundle\Model\JKFile
    indexes:
        name_index:
            columns: [ id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        fileName:
            type: string
            length: 255
        fileExtension:
            type: string
            length: 6
            nullable: true
        fileMine:
            type: string
            length: 128
        fileSize:
            type: interger
            nullable: true
        filePath:
            type: string
            length: 255
        fileSlug:
            type: string
            length: 255
        public:
            type: boolean
            nullable: true
            options:
                default: 0
        deleted:
            type: boolean
            nullable: true
            options:
                default: 0
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateDate ]
        preUpdate: [ updateDate ]
