<?php

namespace Fabgg\JukeboxBundle\Repository;

/**
 * JKDocumentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JKAccessLogRepository extends \Doctrine\ORM\EntityRepository
{
}
