<?php

namespace Fabgg\JukeboxBundle\Repository;

/**
 * JKFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JKFileRepository extends \Doctrine\ORM\EntityRepository
{
}
